version: '3'

services:
  consul:
    image: consul:latest
    container_name: consul
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_HTTP_TOKEN="supersecure"
    ports:
      - 8300:8300/tcp
      - 8301:8301/tcp
      - 8301:8301/udp
      - 8302:8302/tcp
      - 8302:8302/udp
      - 8400:8400/tcp
      - 8500:8500/tcp
      - 8600:8600/tcp
      - 8600:8600/udp
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  consul-data:

